- name: Create EC2 security group
  ec2_group:
    name: tagger_rest_sg
    description: EC2 tagger REST (sitting behind ELB)
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"

    rules:
    - proto: tcp
      from_port: 80
      to_port: 80
      group_name: elb_tagger_rest_public_sg

    - proto: tcp
      from_port: 80
      to_port: 80
      group_name: elb_tagger_rest_sg

    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0

    rules_egress:
    - proto: all
      from_port: all
      to_port: all
      cidr_ip: 0.0.0.0/0
