- name: Create route53 (DNS) zone
  route53_zone:
      state: present
      zone: "{{ dns_zone }}"
      vpc_id: "{{ vpc_id }}"
      vpc_region: "{{ region }}"
  register: _route53

- name: Provision EC2 instance
  ec2:
    keypair: "{{ key_pair_name }}"
    group: "{{ security_group }}"
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnet }}"
    instance_type: "{{ instance_type }}"
    instance_profile_name: "{{ iam_role }}"
    image: "{{ image }}"
    wait: True
    exact_count: 1
    count_tag:
      Name: "{{ name }}"
    instance_tags:
      Name: "{{ name }}"
  register: _ec2

- name: Add all instance public IPs to host group
  add_host: hostname={{ item.public_ip }} groups=tag_Name_{{ name }}
  with_items: _ec2.instances

- name: Wait for the instances to boot by checking the ssh port
  wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
  with_items: _ec2.instances

- name: Add private IP to route53 (DNS)
  route53:
      command: create
      zone: "{{ _route53.set.name }}"
      record: "{{ name }}.{{ _route53.set.name }}"
      private_zone: "{{ _route53.set.private_zone }}"
      hosted_zone_id: "{{ _route53.set.zone_id }}"
      overwrite: True
      type: A
      value: "{{ item.private_ip }}"
  with_items: _ec2.instances