- name: Create EC2 security group
  ec2_group:
    name: job_tagger_sg
    description: EC2 job tagger - polls SQS and sends tags to REST (ELB)
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"

    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0

    rules_egress:
    - proto: all
      from_port: all
      to_port: all
      cidr_ip: 0.0.0.0/0
